package com.app.ecolive.login_module.model

import java.io.Serializable

data class UserModel(
    val __v: Int,
    val _id: String,
    val countryCode: String,
    val createdAt: String,
    val deviceId: String,
    val deviceType: String,
    val driverOnDuty: Boolean,
    val email: String,
    val fcmToken: String,
    val firstName: String,
    val getNotification: Boolean,
    var isRider: Boolean,
    val isRiderVerified: Boolean,
    val isSocialLogin: Boolean,
    var isVendor: Boolean,
    val isVendorVerified: Boolean,
    val language: String,
    val lastName: String,
    val latitude: String,
    val longitude: String,
    val mobileNumber: String,
    val notificationFound: Boolean,
    val role: String,
    val socialLoginId: String,
    val socialLoginType: String,
    val status: String,
    val updatedAt: String,
    val accessToken: String,
    val address: String?,
    val checkEmailVerified: CheckEmailVerified?,
    val checkMobileVerified: CheckMobileVerified?,
    val profilePicture: String?,
    val refereshToken: String,
    var isDoctor: Boolean = false,
    var isPharmacy: Boolean = false,
    ) : Serializable